### ISSUE TITLE
Save scene if there were changes

### ISSUE THREAD

**Issue by ungi** [SlicerIGT/LumpNav#56]
Add a parameter to the parameter node that tells if it has been changed since last save or not. If user wants to exit with unsaved changes, then save automatically.

**Comment by JoshEhrlich** [comment]
I am a little confused on this. Here is my pseudo code:
-Add observer that watches parameter node (which event?)
-Call function when changed that sets a boolean variable called unsavedData to True/False when the parameter node is changed and the scene is not saved. 
- within the "exit" function, add a check of this variable. Save automatically if not being done by user

My only worry is that won't this start happening even when we are developing? Maybe we could go over some use-cases together.

**Comment by lassoan** [comment]
You don't need to add an observer to notice changes. Whenever you modify a node, its modified timestamp is updated automatically. If the node's modified timestamp > last save's timestamp then you need to save it. To save the timestamp of the last save, you can create a timestamp object and whenever you saved, call `Modified()`.

```python
# Have a member variable that stores the last save time
saveTime = vtk.vtkTimeStamp();

# Call this when the data set is loaded and each time you save the data set
saveTime.Modified()

# Check if save is needed:
needToSave = (parameterNode.GetMTime() > saveTime.GetMTime())
```

**Comment by JoshEhrlich** [comment]
Wonderful, thank you very much!
