### ISSUE TITLE
Add Exit button

### ISSUE THREAD

**Issue by lassoan** [SlicerIGT/LumpNav#6]
Add Exit button. It should not be in a very prominent position - maybe in the advanced tab?

**Comment by kanyala** [comment]
I added an exit button to advance tab, exit works correctly. Though it is not the same as the slicer quits invoking the exit popup. How may I invoke the popup? Is it needed or a simple exit is ok?

**Comment by lassoan** [comment]
It would be safer to show a confirmation popup. You should be able to track down in the Slicer source code what action is called on File / Exit menu.

**Comment by kanyala** [comment]
ok, it works.
thanks
L

2015-09-02 23:59 GMT+02:00 Andras Lasso <notifications@github.com>:

**Comment by adamrankin** [comment]
Thank you! Now instead of a beep, how about [nyancat](https://www.youtube.com/watch?v=wZZ7oFKsKzY). to notify you of PLUS disconnect!! (joke)
